# Debug set to true in order to debug high-layer code.
# CFG Configuration
CFG:
  DEBUG: false
  num_workers: 2
  train_batch_size: 256
  valid_batch_size: 128

  # Train configuration
  TRAIN_TOKENIZER: false
  PREPROCESS: false
  user_name: "snoop2head"
  num_epochs: 10 # validation loss is increasing after 5 epochs
  max_token_length: 64
  stopwords: []
  learning_rate: 5e-4
  weight_decay: 1e-2 # https://paperswithcode.com/method/weight-decay
  adam_betas: (0.9, 0.98)
  epsilon: 1e-9

  # Translation settings
  src_vocab_size: 10000
  tgt_vocab_size: 10000
  src_language: "ko"
  tgt_language: "en"

  # root path
  ROOT_PATH: "."

  # set best model path
  model_path: "./best-eval-loss-model-10-epochs.pt"
